export { HeroSection } from "./HeroSection";
export { ApplicationsSection } from "./ApplicationsSection";
export { AISection } from "./AISection";
export { AutomationSection } from "./AutomationSection";
export { IntegrationSection } from "./IntegrationSection";
export { ProcessSection } from "./ProcessSection";
export { SecuritySection } from "./SecuritySection";
export { FinalCTASection } from "./FinalCTASection";
export { Workflow } from "./Workflow";
